In [ ]:
# Data Toolkit 

In [3]:
'''Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each
method and the final output after each method.'''

# Ans
import numpy as np
# Method 1: Using numpy.array
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array created using numpy.array:")
print(array1)


# Method 2: Using numpy.zeros and then filling values
array2 = np.zeros((3, 3), dtype=int)
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]
array2[2] = [7, 8, 9]
print("\nArray created using numpy.zeros and then filling values:")
print(array2)


# Method 3: Using numpy.full with a pre-defined pattern
array3 = np.full((3, 3), 0)  # Initialize with zeros
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]
array3[2] = [7, 8, 9]
print("\nArray created using numpy.full with a pre-defined pattern:")
print(array3)

Array created using numpy.array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array created using numpy.zeros and then filling values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array created using numpy.full with a pre-defined pattern:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
'''2.Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and
Reshape that 1D array into a 2D array.'''

# Ans
import numpy as np

# Generate an array of 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array with shape (10, 10)
array_2d = array_1d.reshape((10, 10))

print("1D array of 100 evenly spaced numbers between 1 and 10:")
print(array_1d)

print("\nReshaped 2D array (10x10):")
print(array_2d)


1D array of 100 evenly spaced numbers between 1 and 10:
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.0909090

In [5]:
'''4. Generate a 3 x 3 array with random floating-point numbers Petween 5 and 20. when, round each number in
the array to 2 decimal places.'''

# Ans
import numpy as np
# Generate a 3x3 array with random floating-point numbers between 5 and 20
array = np.random.uniform(5, 20, (3, 3))
# Round each number in the array to 2 decimal places
rounded_array = np.round(array, 2)
print("Generated 3x3 array with random floating-point numbers between 5 and 20:")
print(array)
print("\nArray with each number rounded to 2 decimal places:")
print(rounded_array)

Generated 3x3 array with random floating-point numbers between 5 and 20:
[[ 6.09762449 19.97622056  8.55121988]
 [ 6.08805309 10.98816604  9.57455426]
 [14.15816562 15.80489787  8.97512314]]

Array with each number rounded to 2 decimal places:
[[ 6.1  19.98  8.55]
 [ 6.09 10.99  9.57]
 [14.16 15.8   8.98]]


In [6]:
'''5. Create a NumPy array with random integers between 1 and 10 of shape (5 , 6 ). After creating the array
perform the following operations:
 a)Extract all even integers from array.
 b)Extract all odd integers from array.'''

# Ans
import numpy as np
# Create a NumPy array with random integers between 1 and 10 of shape (5, 6)
array = np.random.randint(1, 11, (5, 6))
# Extract all even integers from the array
even_integers = array[array % 2 == 0]
# Extract all odd integers from the array
odd_integers = array[array % 2 != 0]
print("Generated array (5x6) with random integers between 1 and 10:")
print(array)
print("\nEven integers extracted from the array:")
print(even_integers)
print("\nOdd integers extracted from the array:")
print(odd_integers)

Generated array (5x6) with random integers between 1 and 10:
[[ 6  1 10  4  4  1]
 [ 6  4  4  4 10  4]
 [ 1  9 10  4  5  7]
 [ 2  3  9  2  4 10]
 [10  6  6  3  6  4]]

Even integers extracted from the array:
[ 6 10  4  4  6  4  4  4 10  4 10  4  2  2  4 10 10  6  6  6  4]

Odd integers extracted from the array:
[1 1 1 9 5 7 3 9 3]


In [7]:
'''6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the
following operations:
 a) Find the indices of the maximum values along each depth level (third axis).
 b) Perform element-wise multiplication of between both array'''

# Ans
import numpy as np
# Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10
array1 = np.random.randint(1, 11, (3, 3, 3))
array2 = np.random.randint(1, 11, (3, 3, 3))
# Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array1, axis=2)
# Perform element-wise multiplication of both arrays
elementwise_multiplication = np.multiply(array1, array2)
print("First 3D array (array1):")
print(array1)
print("\nSecond 3D array (array2):")
print(array2)
print("\nIndices of the maximum values along each depth level in array1:")
print(max_indices)
print("\nElement-wise multiplication of array1 and array2:")
print(elementwise_multiplication)

First 3D array (array1):
[[[ 8  8  1]
  [ 4  2  8]
  [ 1 10  6]]

 [[ 9  4  8]
  [ 6  8  5]
  [ 2 10  7]]

 [[ 6  1  3]
  [ 9  3  5]
  [ 2  8  7]]]

Second 3D array (array2):
[[[6 6 1]
  [5 3 4]
  [7 9 7]]

 [[5 8 6]
  [4 9 3]
  [5 5 9]]

 [[3 7 8]
  [1 2 6]
  [1 1 3]]]

Indices of the maximum values along each depth level in array1:
[[0 2 1]
 [0 1 1]
 [0 0 1]]

Element-wise multiplication of array1 and array2:
[[[48 48  1]
  [20  6 32]
  [ 7 90 42]]

 [[45 32 48]
  [24 72 15]
  [10 50 63]]

 [[18  7 24]
  [ 9  6 30]
  [ 2  8 21]]]


In [12]:
'''7.Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and
convert it to a numeric data type. Also display the taPle attributes and data types of each column.'''

# Ans
import pandas as pd
import numpy as np

# Read the 'People Data.csv' file
file_path = 'People Data.csv'
df = pd.read_csv(file_path)

# Display the table attributes and data types of each column before transformation
print("Attributes and Data Types before transformation:")
print(df.info())

# Function to clean and transform the 'Phone' column
def clean_phone(phone):
    if pd.isna(phone):
        return np.nan
    return ''.join(filter(str.isdigit, str(phone)))

# Clean and transform the 'Phone' column
df['Phone'] = df['Phone'].apply(clean_phone)

# Convert the 'Phone' column to numeric data type, coercing errors to NaN
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')

# Display the table attributes and data types of each column after transformation
print("\nAttributes and Data Types after transformation:")
print(df.info())


Attributes and Data Types before transformation:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Index          1000 non-null   int64 
 1   User Id        1000 non-null   object
 2   First Name     1000 non-null   object
 3   Last Name      1000 non-null   object
 4   Gender         1000 non-null   object
 5   Email          1000 non-null   object
 6   Phone          979 non-null    object
 7   Date of birth  1000 non-null   object
 8   Job Title      1000 non-null   object
 9   Salary         1000 non-null   int64 
dtypes: int64(2), object(8)
memory usage: 78.2+ KB
None

Attributes and Data Types after transformation:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          1000 non-n

In [35]:
'''8.Perform the following tasks using people dataset:
 a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
 c) Display the first 10 rows of the filtered dataset.
 d) Extract the ‘Salary’ column as a Series and display its last 5 value.'''

# Ans
import pandas as pd
# Read the 'People Data.csv' file, skipping the first 50 rows
file_path = 'People Data.csv'
df = pd.read_csv(file_path, skiprows=50)
# Display the first few rows of the DataFrame to verify
df.head()


50  afF3018e9cdd1dA     George  Mercer  Female  \
0  51  CccE5DAb6E288e5         Jo  Zavala    Male   
1  52  DfBDc3621D4bcec     Joshua   Carey  Female   
2  53  f55b0A249f5E44D     Rickey   Hobbs  Female   
3  54  Ed71DcfaBFd0beE      Robyn  Reilly    Male   
4  55  FDaFD0c3f5387EC  Christina  Conrad    Male   

  douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0         pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1    dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2    ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3   carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4   fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   

  Human resources officer   70000  
0            Nurse, adult   80000  
1     Seismic interpreter   70000  
2               Barrister   60000  
3    Engineer, structural  100000  
4         Producer, radio   50000

In [34]:
# Read specific columns from the 'People Data.csv' file, skipping the first 50 rows
file_path = 'People Data.csv'
selected_columns = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
df = pd.read_csv(file_path,usecols=selected_columns)
# Display the first few rows of the DataFrame to verify
df.head()

Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000

In [37]:
# Display the first 10 rows of the filtered dataset
print("First 10 rows of the filtered dataset:")
df.head(10)

First 10 rows of the filtered dataset:


50  afF3018e9cdd1dA     George   Mercer  Female  \
0  51  CccE5DAb6E288e5         Jo   Zavala    Male   
1  52  DfBDc3621D4bcec     Joshua    Carey  Female   
2  53  f55b0A249f5E44D     Rickey    Hobbs  Female   
3  54  Ed71DcfaBFd0beE      Robyn   Reilly    Male   
4  55  FDaFD0c3f5387EC  Christina   Conrad    Male   
5  56  998C3Fda97EfAff     Shelby     Cole    Male   
6  57  D7040faD2d368d8      Steve  Donovan    Male   
7  58  3CEf7FDfACa48b7       Gina   Little  Female   
8  59  239dbABfd1d1B1e     Connie   Dawson  Female   
9  60  4e03dA0BCAc82e3      Aaron     Page    Male   

  douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0         pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1    dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2    ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3   carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4   fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   
5       kaneaudrey@example.org            663-280-5834  18-08-1975   
6    rebekahsantos@example.net                     NaN  14-04-1935   
7          craig28@example.com       125.219.3673x0076  07-10-1954   
8   connercourtney@example.net      650-748-3069x64529  21-07-1979   
9   harrygallagher@example.com        849.500.6331x717  11-03-1981   

           Human resources officer   70000  
0                     Nurse, adult   80000  
1              Seismic interpreter   70000  
2                        Barrister   60000  
3             Engineer, structural  100000  
4                  Producer, radio   50000  
5           Therapist, nutritional   85000  
6                 Paediatric nurse   65000  
7              Production engineer   60000  
8  Accountant, chartered certified   60000  
9                    Administrator   60000